In [1]:
from pyhive import hive

In [2]:
import pandas as pd

In [3]:
conn = hive.connect('zachary-hdp.demo.continuum.io')

In [4]:
cursor = conn.cursor()

In [5]:
cursor.execute('SELECT * FROM vehicle_data LIMIT 5')

In [6]:
print cursor.fetchall()

[(21, u'Alfa Romeo', u'Spider Veloce 2000', 1985, -1500, u''), (11, u'Ferrari', u'Testarossa', 1985, -8500, u'T'), (27, u'Dodge', u'Charger', 1985, 250, u''), (11, u'Dodge', u'B150/B250 Wagon 2WD', 1985, -8500, u''), (19, u'Subaru', u'Legacy AWD Turbo', 1993, -4250, u'')]

In [7]:
cursor.execute('SELECT * FROM citibike_trips LIMIT 10')

In [8]:
output = cursor.fetchall()

In [9]:
print output

[(362, u'"2017-09-01 00:00:17"', u'"2017-09-01 00:06:19"', 3331, u'"Riverside Dr & W 104 St"', 40.801342, -73.971146, 3328, u'"W 100 St & Manhattan Ave"', 40.795, -73.9645, 14530, u'"Subscriber"', 1993, 1), (188, u'"2017-09-01 00:00:21"', u'"2017-09-01 00:03:30"', 3101, u'"N 12 St & Bedford Ave"', 40.7208, -73.95485, 3100, u'"Nassau Ave & Newell St"', 40.72481, -73.947525, 15475, u'"Subscriber"', 1988, 1), (305, u'"2017-09-01 00:00:25"', u'"2017-09-01 00:05:30"', 3140, u'"1 Ave & E 78 St"', 40.771404, -73.953514, 3141, u'"1 Ave & E 68 St"', 40.765007, -73.95818, 30346, u'"Subscriber"', 1969, 1), (223, u'"2017-09-01 00:00:52"', u'"2017-09-01 00:04:36"', 236, u'"St Marks Pl & 2 Ave"', 40.72842, -73.98714, 473, u'"Rivington St & Chrystie St"', 40.7211, -73.99193, 28056, u'"Subscriber"', 1993, 1), (758, u'"2017-09-01 00:01:01"', u'"2017-09-01 00:13:40"', 3427, u'"Lafayette St & Jersey St"', 40.724304, -73.99601, 3431, u'"E 35 St & 3 Ave"', 40.746525, -73.97788, 25413, u'"Subscriber"', 1987, 1), (2089, u'"2017-09-01 00:01:20"', u'"2017-09-01 00:36:09"', 3016, u'"Kent Ave & N 7 St"', 40.720367, -73.96165, 3358, u'"Garfield Pl & 8 Ave"', 40.671196, -73.97484, 17584, u'"Subscriber"', 1975, 2), (121, u'"2017-09-01 00:01:22"', u'"2017-09-01 00:03:23"', 3357, u'"W 106 St & Amsterdam Ave"', 40.800835, -73.966446, 3343, u'"W 107 St & Columbus Ave"', 40.799755, -73.96211, 28581, u'"Subscriber"', 1990, 1), (408, u'"2017-09-01 00:01:39"', u'"2017-09-01 00:08:27"', 470, u'"W 20 St & 8 Ave"', 40.743454, -74.00004, 388, u'"W 26 St & 10 Ave"', 40.749718, -74.00295, 30470, u'"Subscriber"', 1961, 1), (485, u'"2017-09-01 00:01:41"', u'"2017-09-01 00:09:46"', 513, u'"W 56 St & 10 Ave"', 40.768253, -73.98864, 529, u'"W 42 St & 8 Ave"', 40.75757, -73.99098, 18150, u'"Subscriber"', 1984, 1), (220, u'"2017-09-01 00:01:40"', u'"2017-09-01 00:05:21"', 405, u'"Washington St & Gansevoort St"', 40.739323, -74.00812, 358, u'"Christopher St & Greenwich St"', 40.732914, -74.00711, 28200, u'"Subscriber"', 1992, 1)]

In [20]:
pd.read_sql('SELECT * FROM citibike_trips LIMIT 10', conn)

,citibike_trips.tripduration,citibike_trips.starttime,citibike_trips.stoptime,citibike_trips.start_station_id,citibike_trips.start_station_name,citibike_trips.start_station_latitutude,citibike_trips.start_station_longitude,citibike_trips.end_station_id,citibike_trips.end_station_name,citibike_trips.end_station_latitude,citibike_trips.end_station_longitude,citibike_trips.bikeid,citibike_trips.usertype,citibike_trips.birth_year,citibike_trips.gender
0,362,"""2017-09-01 00:00:17""","""2017-09-01 00:06:19""",3331,"""Riverside Dr & W 104 St""",40.801342,-73.971146,3328,"""W 100 St & Manhattan Ave""",40.795000,-73.964500,14530,"""Subscriber""",1993,1
1,188,"""2017-09-01 00:00:21""","""2017-09-01 00:03:30""",3101,"""N 12 St & Bedford Ave""",40.720800,-73.954850,3100,"""Nassau Ave & Newell St""",40.724810,-73.947525,15475,"""Subscriber""",1988,1
2,305,"""2017-09-01 00:00:25""","""2017-09-01 00:05:30""",3140,"""1 Ave & E 78 St""",40.771404,-73.953514,3141,"""1 Ave & E 68 St""",40.765007,-73.958180,30346,"""Subscriber""",1969,1
3,223,"""2017-09-01 00:00:52""","""2017-09-01 00:04:36""",236,"""St Marks Pl & 2 Ave""",40.728420,-73.987140,473,"""Rivington St & Chrystie St""",40.721100,-73.991930,28056,"""Subscriber""",1993,1
4,758,"""2017-09-01 00:01:01""","""2017-09-01 00:13:40""",3427,"""Lafayette St & Jersey St""",40.724304,-73.996010,3431,"""E 35 St & 3 Ave""",40.746525,-73.977880,25413,"""Subscriber""",1987,1
5,2089,"""2017-09-01 00:01:20""","""2017-09-01 00:36:09""",3016,"""Kent Ave & N 7 St""",40.720367,-73.961650,3358,"""Garfield Pl & 8 Ave""",40.671196,-73.974840,17584,"""Subscriber""",1975,2
6,121,"""2017-09-01 00:01:22""","""2017-09-01 00:03:23""",3357,"""W 106 St & Amsterdam Ave""",40.800835,-73.966446,3343,"""W 107 St & Columbus Ave""",40.799755,-73.962110,28581,"""Subscriber""",1990,1
7,408,"""2017-09-01 00:01:39""","""2017-09-01 00:08:27""",470,"""W 20 St & 8 Ave""",40.743454,-74.000040,388,"""W 26 St & 10 Ave""",40.749718,-74.002950,30470,"""Subscriber""",1961,1
8,485,"""2017-09-01 00:01:41""","""2017-09-01 00:09:46""",513,"""W 56 St & 10 Ave""",40.768253,-73.988640,529,"""W 42 St & 8 Ave""",40.757570,-73.990980,18150,"""Subscriber""",1984,1
9,220,"""2017-09-01 00:01:40""","""2017-09-01 00:05:21""",405,"""Washington St & Gansevoort St""",40.739323,-74.008120,358,"""Christopher St & Greenwich St""",40.732914,-74.007110,28200,"""Subscriber""",1992,1

In [21]:
pd.read_sql('SELECT * FROM nyc_weather LIMIT 10', conn)

,nyc_weather.ts_year,nyc_weather.ts_month,nyc_weather.ts_day,nyc_weather.ts_hour,nyc_weather.ts_minute,nyc_weather.humidity,nyc_weather.visibility,nyc_weather.neareststormbearing,nyc_weather.summary,nyc_weather.ozone,...,nyc_weather.windspeed,nyc_weather.windbearing,nyc_weather.neareststormdistance,nyc_weather.precipprobability,nyc_weather.uvindex,nyc_weather.pressure,nyc_weather.cloudcover,nyc_weather.icon,nyc_weather.dewpoint,nyc_weather.temperature
0,2017,7,13,5,30,0.81,9.56,9.0,Clear,294.99,...,4.14,275,37.0,0.0,0.0,1015.08,0.13,clear-night,71.95,78.31
1,2017,3,20,14,40,0.59,10.00,312.0,Clear,358.52,...,8.77,337,101.0,0.0,NaN,1020.97,0.05,clear-day,26.06,39.38
2,2017,3,11,4,45,0.50,10.00,179.0,Partly Cloudy,415.12,...,14.10,307,10.0,0.0,NaN,1015.22,0.38,partly-cloudy-night,8.71,24.58
3,2017,8,29,5,15,0.75,8.86,193.0,Overcast,301.66,...,8.25,80,137.0,0.0,0.0,1023.90,0.97,cloudy,55.34,63.37
4,2017,5,9,3,20,0.55,10.00,NaN,Mostly Cloudy,394.52,...,2.05,120,0.0,0.0,NaN,1013.61,0.75,partly-cloudy-night,37.38,53.28
5,2017,2,1,18,30,0.58,10.00,176.0,Mostly Cloudy,364.45,...,8.57,245,4.0,0.0,NaN,1013.36,0.80,partly-cloudy-day,32.22,46.20
6,2017,6,15,15,35,0.49,10.00,147.0,Clear,314.65,...,9.79,147,97.0,0.0,8.0,1018.18,0.22,clear-day,54.68,75.08
7,2017,11,15,15,50,0.63,10.00,282.0,Clear,277.41,...,5.83,59,199.0,0.0,2.0,1024.81,0.03,clear-day,32.21,43.84
8,2017,3,22,2,20,0.53,10.00,284.0,Partly Cloudy,360.41,...,4.36,278,15.0,0.0,NaN,1011.46,0.50,partly-cloudy-night,30.86,47.32
9,2017,4,8,13,5,0.56,10.00,357.0,Partly Cloudy,386.31,...,9.84,288,111.0,0.0,NaN,1008.83,0.48,partly-cloudy-day,28.68,43.21

In [22]:
pd.read_sql('SELECT * FROM nyc_weather WHERE TS_year=2016 LIMIT 10', conn)

,nyc_weather.ts_year,nyc_weather.ts_month,nyc_weather.ts_day,nyc_weather.ts_hour,nyc_weather.ts_minute,nyc_weather.humidity,nyc_weather.visibility,nyc_weather.neareststormbearing,nyc_weather.summary,nyc_weather.ozone,...,nyc_weather.windspeed,nyc_weather.windbearing,nyc_weather.neareststormdistance,nyc_weather.precipprobability,nyc_weather.uvindex,nyc_weather.pressure,nyc_weather.cloudcover,nyc_weather.icon,nyc_weather.dewpoint,nyc_weather.temperature
0,2016,9,29,10,45,0.82,9.59,9,Overcast,291.75,...,9.32,50,334.0,0.00,None,1025.20,1.00,No Data,56.07,61.46
1,2016,7,27,12,10,0.64,9.67,23,Clear,300.19,...,3.00,0,270.0,0.00,None,1013.78,0.17,No Data,65.00,78.06
2,2016,9,20,0,5,0.90,9.30,14,Mostly Cloudy,269.00,...,2.90,189,115.0,0.00,None,1017.51,0.66,No Data,66.51,69.50
3,2016,9,9,6,45,0.73,9.39,14,Partly Cloudy,266.65,...,5.56,242,325.0,0.00,None,1009.81,0.36,No Data,70.07,79.62
4,2016,7,21,12,20,0.72,9.39,66,Clear,320.91,...,4.32,276,260.0,0.00,None,1021.58,0.04,No Data,64.81,74.63
5,2016,9,24,21,20,0.39,10.00,132,Clear,288.05,...,6.51,348,240.0,0.00,None,1019.53,0.07,No Data,44.71,70.72
6,2016,10,19,9,45,0.86,9.35,92,Partly Cloudy,274.57,...,4.43,225,314.0,0.00,None,1011.68,0.38,No Data,62.38,66.87
7,2016,8,25,11,30,0.80,9.70,11,Clear,290.31,...,5.64,199,132.0,0.00,None,1019.90,0.23,No Data,63.88,70.29
8,2016,11,20,8,20,0.89,7.10,0,Mostly Cloudy,264.50,...,9.57,282,NaN,0.11,None,1000.77,0.76,No Data,35.52,38.39
9,2016,11,1,12,25,0.83,9.26,184,Clear,275.13,...,2.19,42,322.0,0.00,None,1028.08,0.13,No Data,36.59,41.38